export enum StatusPedido {
  PENDENTE = 'PENDENTE',

  APROVADO = 'APROVADO',

  PARC_APROVADO = 'PARC_APROVADO',

  REPROVADO = 'REPROVADO',

  EXPIRADO = 'EXPIRADO',

  CANCELADO = 'CANCELADO',

  ESTORNADO = 'ESTORNADO',
}
